# 配置mysql的驱动包的位置
db.mysql.location: C:/Users/Administrator/.m2/repository/mysql/mysql-connector-java/5.1.47/mysql-connector-java-5.1.47.jar

# druid数据库连接池的配置
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
#com.mysql.cj.jdbc.Driver
spring.datasource.druid.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.druid.url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.druid.username: root
spring.datasource.druid.password: Xie123456@
spring.datasource.druid.max-active: 20
spring.datasource.druid.max-wait: 6000
spring.datasource.druid.min-idle: 1
spring.datasource.druid.test-on-borrow: true
spring.datasource.druid.test-on-return: true

#定义mapper文件的位置 将dao与对应mapper文件关联起来
mybatis.mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml

#图片服务器地址前缀
# imageHost: http://localhost:8080/uploadpic
imageHost: http://39.105.149.25/img



#分页配置
pagehelper.helper-dialect: mysql
pagehelper.reasonable: true
pagehelper.support-methods-arguments: true
pagehelper.params: countSql


#ftp访问服务器配置
ftp.server.ip: 39.105.149.25
ftp.server.user: ftpuser
ftp.server.password: 123456


# 订单关闭时间 1小时
close.order.time: 1

#####redis配置开始###########
### 最大连接数
redis.max.total: 20
### 最大空闲数
redis.max.idle: 10
### 最小空闲数
redis.min.idle: 2
### ip
redis.ip: 39.105.149.25
### port
redis.port: 5379
#在获取实例时,校验实例是否有效
redis.test.borrow: true
#在把jedis实例放回连接池时,校验实例是否有效
redis.test.return: true
# 密码
redis.password: 123456
####redis配置结束###############